### ISSUE TITLE
encryption

### ISSUE THREAD

**Issue by DJafari** [fdoyle/EasyDatastore#3]
it's to be good that add encryption method to enctypt values

**Comment by fdoyle** [comment]
There are a number of SharedPrefs implementations that support encryption, if you pass one of these in, EasyDatastore will happily take advantage. 

https://github.com/scottyab/secure-preferences
https://github.com/willowtreeapps/OAK (Contains an encrypted sharedprefs impelmentation, I've been using it for a few years and it's worked great)
